### ISSUE TITLE
Message is empty

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/telegram_ros#16]
```
[ERROR][/hero/telegram_ros_bridge][1580247019.209342]: bad callback: <bound method TelegramROSBridge._ros_string_callback of <__main__.TelegramROSBridge object at 0x7f308fa3c610>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/amigo/ros/kinetic/system/src/telegram_ros/scripts/telegram_ros_bridge", line 133, in wrapper
    callback_function(self, msg)
  File "/home/amigo/ros/kinetic/system/src/telegram_ros/scripts/telegram_ros_bridge", line 155, in _ros_string_callback
    self._telegram_updater.bot.send_message(self._telegram_chat_id, msg.data)
  File "/home/amigo/.local/lib/python2.7/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/home/amigo/.local/lib/python2.7/site-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/home/amigo/.local/lib/python2.7/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/home/amigo/.local/lib/python2.7/site-packages/telegram/utils/request.py", line 223, in _request_wrapper
    raise BadRequest(message)
BadRequest: Message text is empty
```

**Comment by MatthijsBurgh** [comment]
```
[ERROR][/telegram_ros_bridge][1652182028.871733]: bad callback: <bound method TelegramROSBridge._ros_string_callback of <telegram_ros.bridge.TelegramROSBridge object at 0x7f09636bf430>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/amigo/ros/noetic/system/src/telegram_ros/src/telegram_ros/bridge.py", line 59, in wrapper
    callback_function(self, msg)
  File "/home/amigo/ros/noetic/system/src/telegram_ros/src/telegram_ros/bridge.py", line 205, in _ros_string_callback
    self._telegram_updater.bot.send_message(self._telegram_chat_id, msg.data)
  File "/home/amigo/.local/lib/python3.8/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/amigo/.local/lib/python3.8/site-packages/telegram/bot.py", line 522, in send_message
    return self._message(  # type: ignore[return-value]
  File "/home/amigo/.local/lib/python3.8/site-packages/telegram/ext/extbot.py", line 200, in _message
    result = super()._message(
  File "/home/amigo/.local/lib/python3.8/site-packages/telegram/bot.py", line 336, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/amigo/.local/lib/python3.8/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/amigo/.local/lib/python3.8/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/amigo/.local/lib/python3.8/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message text is empty
```
